# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
# Default build settings

[build]
  publish = "public"
  command = "hugo --gc"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"
  GO_VERSION = "1.18"

# section redirects
[[redirects]]
  from = "/cd-as-a-service/release-notes/"
  to = "https://armory.releases.live/?filter=eyJ0aXRsZU9yRGVzY3JpcHRpb24iOiIiLCJzY29wZSI6WyJDRC1hcy1hLVNlcnZpY2UiXSwidHlwZSI6W10sImZpZWxkcyI6W119/"
  force = true # ensure this always redirects because the  manualLink does not work for users typing in the URL

[[redirects]]
  from = "/deployment/preview-deployed-service/" # this page contains manualLinkRelRef in frontmatter
  to = "/reference/deployment/config-preview-link/"
  force = true # preview-deployed-service shouldn't appear in search engine results, but if it does, always redirect (same with users typing in directly)

# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude =[
    './public/includes/',
    './public/categories/',
    './public/tags/',
    './public/favicons/',
    './public/404.html',
    './public/deployment/preview-deployed-service/'
  ]
  # set baseURL because we aren't configuring a custom domain in Netlify
  # Although the above is called base URL this actually ends up being the hostname in the sitemap and as such trying to use a URL like http://example.com/en/ will results in http://example.com/
  # https://github.com/netlify-labs/netlify-plugin-sitemap
  baseUrl = "https://developer.armory.io/docs/"
  
  # append missing trailing slash to prettyURL
  trailingSlash = true
  changeFreq = "daily"
  priority = 0.5


# headers  https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# https://cloud-armory.slack.com/archives/CH4RVCCTS/p1608572781420500
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
