# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
# Default build settings
[build]
  publish = "public"
  command = "hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"
  GO_VERSION = "1.18"

# section redirects


# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  
  # append missing trailing slash to prettyURL
  trailingSlash = true
  changeFreq = "daily"
  priority = 0.5


# headers  https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# https://cloud-armory.slack.com/archives/CH4RVCCTS/p1608572781420500
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
